#!/bin/sh

function check_version {
  $1

  if [ $? -ne 0 ]; then
    exit 1;
  fi
}

brew bundle

check_version "git --version"
check_version "ruby -v"
check_version "gem -v"
check_version "bundle -v"
check_version "psql --version"

bundle
bundle binstubs rubocop --force
bundle binstubs puma --force

cp -n .env.example .env
cp -n config/database.yml.example config/database.yml

rake db:create
